package pe.edu.udaff.entities;
// Generated 29/04/2019 08:30:40 AM by Hibernate Tools 5.3.0.Beta2

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer idProducto;
	private Proveedor proveedor;
	private String nombre;
	private int stock;
	private double precioCompra;
	private double precioVenta;

	public Producto() {
	}

	public Producto(Proveedor proveedor, String nombre, int stock, double precioCompra, double precioVenta) {
		this.proveedor = proveedor;
		this.nombre = nombre;
		this.stock = stock;
		this.precioCompra = precioCompra;
		this.precioVenta = precioVenta;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	public double getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(double precioCompra) {
		this.precioCompra = precioCompra;
	}

	public double getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(double precioVenta) {
		this.precioVenta = precioVenta;
	}

}
